### PR TITLE
direct_link: change fembed using function instead

### PR DESCRIPTION
**Pull request by troublescope**
``fembed`` is to many url, isn't relevan to add in list

### CODE REVIEW

**Comment by junedkh** [comment]
improve it brother this is not enough

**Comment by troublescope** [comment]
> improve it brother this is not enough

what is not enough? 
this will checking all url if fembed checker return True then will return to fembed downloader. also are you already tested?

**Comment by junedkh** [comment]
i will test it.
give me urls

**Comment by junedkh** [comment]
i will improve it with my method

**Pull request closed without merging**
